name: Fetch and Autocommit v1
on:
  schedule:
    # Run at 01 and 13 UTC every day
    - cron: '30 4/12 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Fetch and save launches
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/launches'
        file: '_data/launches.json'
    - name: Fetch and save cores
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/cores'
        file: '_data/cores.json'
    - name: Fetch and save payloads
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/payloads'
        file: '_data/payloads.json'
    - name: Fetch and save launchpads
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/launchpads'
        file: '_data/launchpads.json'
    - name: Fetch and save landpads
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/landpads'
        file: '_data/landpads.json'
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.8.0
    - name: Rebuild pages
      uses: actions/github/script@v3.1.0
      with:
        github-token: ${{ secrets.ACTIONS }}
        script: |
          const build = await github.repos.requestPagesBuild({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return build.data.status;
