name: Update from spacexdata.com
on:
  schedule:
    - cron: '0 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            // Get file for sha
            const file = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: "_data/upcoming.json"
            })
            return file.data
