name: Update from spacexdata.com
on:
  #pull_request_target:
  #  types: [ opened ]
  #  branches: [ main ]
  schedule:
    - cron: '0/10 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.19
        with:
          ENDPOINT: https://api.spacexdata.com/v4/launches
          SAVE_LOCATION: _data
          SAVE_NAME: launches
