name: Update from spacexdata.com
on:
  #pull_request_target:
  #  types: [ opened ]
  #  branches: [ main ]
  schedule:
    - cron: '10 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'https://api.spacexdata.com/v4/launches'
        file: '_data/launches.json'
    - name: list files
      run: ls
