name: Update from spacexdata.com
on:
  #pull_request_target:
  #  types: [ opened ]
  #  branches: [ main ]
  schedule:
    #- cron: '0/10 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Fetch
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/launches'
          file: '_data/launches.json'
      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACTIONS }}
          BRANCH: main
          FOLDER: _data
