name: Fetch Save and Autocommit
on: workflow_dispatch
  #schedule:
    # Run at 01 and 13 UTC every day
    #- cron: '0 1/12 * * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Fetch and save launches
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/launches'
          file: '_data/launches.json'
      - name: Fetch and save cores
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/cores'
          file: '_data/cores.json'
      - name: Fetch and save payloads
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/payloads'
          file: '_data/payloads.json'
      - name: Fetch and save capsules
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/capsules'
          file: '_data/capsules.json'
      - name: Fetch and save dragons
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/dragons'
          file: '_data/dragons.json'
      - name: Fetch and save launchpads
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/launchpads'
          file: '_data/launchpads.json'
      - name: Fetch and save landpads
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://api.spacexdata.com/v4/landpads'
          file: '_data/landpads.json'
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
